name: json_to_freezed
description: An absolute bare-bones web app.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: ">=2.17.6 <3.0.0"

# dependencies:
#   path: ^1.7.0

dev_dependencies:
  build_runner: ^2.4.1
  build_test: ^2.1.7
  build_web_compilers: ^4.0.3
  lints: ^2.0.0
